### ISSUE TITLE
"Cleaning Mesh Failed" Unity Error

### ISSUE THREAD

**Issue by FactionRed** [pickles976/RTS_selection#1]
After following your tutorial on Youtube and double checking against the source code it all works until i try using the DragSelect, tried replacing all the code with the source to make sure i haven't missed anything but still get the same issues
![2020-04-22_20-56-27](https://user-images.githubusercontent.com/14083950/79973964-cc638580-84db-11ea-8dc7-cab1089f8e10.gif)

**Comment by FactionRed** [comment]
Oh iv actually figured out the problem myself, it has something to do with the Raycast going into the void and it not having any way of handling it, iv just put an ignore error thingy in for now as it doesnt seem to actually cause problems

**Comment by pickles976** [comment]
Yeah, that seems to be a pretty common problem. I think I’ll need to make an FAQ section for some of the issues people have been having. I’m glad you got it working!

**Comment by FactionRed** [comment]
it really doesnt seem to cause any actual issues, just throws that error and pauses the editor even tho there really isnt anything wrong (that i an see) and it would put newer people off thinking its a gamebreaking bug or something
