### ISSUE TITLE
I get this error when I attempt to hit play.

### ISSUE THREAD

**Issue by danceblade** [pickles976/RTS_selection#3]
I saw in the video you have a script on your event system called id_dictionary but I don't know what was in it so I can't get past this error,                Assets\global_selection.cs(7,5): error CS0246: The type or namespace name 'id_dictionary' could not be found (are you missing a using directive or an assembly reference?)

**Comment by pickles976** [comment]
just remove the reference to id_dictionary

**Comment by danceblade** [comment]
Thank you for that, now its working but do you have a fix for something else? When I try to drag select my units it creates the ray cast but doesn't create a mesh collider.
